#!/bin/sh
# 设置默认主题 Argon
uci set luci.main.mediaurlbase='/luci-static/argon'

# 启用 AdGuardHome
uci set adguardhome.default.enabled='1'

# 启用 SmartDNS
uci set smartdns.default.enabled='0'

# 启用 Docker
uci set docker.default.data_root='/opt/docker'

uci commit luci
uci commit adguardhome
uci commit smartdns
uci commit docker
